When local and in tmux, do not use clip.exe or xclip

diff --git a/shellfunc/bin/toclip b/shellfunc/bin/toclip
--- a/shellfunc/bin/toclip
+++ b/shellfunc/bin/toclip
@@ -42,20 +42,22 @@ fi
 # handle either local or remote
 if [[ -z $SSH_TTY ]]; then
 
-    # local connection
-    if command -v clip.exe &>/dev/null; then
-        echo -n "$content" | clip.exe
-        exit 0
-    fi
+    if [[ -z $TMUX ]]; then
+        # local connection
+        if command -v clip.exe &>/dev/null; then
+            echo -n "$content" | clip.exe
+            exit 0
+        fi
 
-    if command -v xclip &>/dev/null; then
-        echo -n "$content" | xclip -selection clipboard
-        exit 0
-    fi
+        if command -v xclip &>/dev/null; then
+            echo -n "$content" | xclip -selection clipboard
+            exit 0
+        fi
 
-    echo "clip.exe is not found" >&2
-    echo "xclip is not installed either" >&2
-    exit 1
+        echo "clip.exe is not found" >&2
+        echo "xclip is not installed either" >&2
+        exit 1
+    fi
 
 else
     # remote, have to wrap osc52
