Add the copy pipe to the tmux conf so I can copy in the nested tmux session

diff --git a/shellfunc/bin/toclip b/shellfunc/bin/toclip
--- a/shellfunc/bin/toclip
+++ b/shellfunc/bin/toclip
@@ -36,6 +36,12 @@ else
 
 fi
 
+# # Debug only
+# echo "$(date)" >> /tmp/toclip.log
+# if [[ -n $TOCLIP_HOST_TMUX ]]; then
+#     echo "$(date)" >> /tmp/toclipt.log
+# fi
+
 # handle the no input error
 if [[ -z $content ]]; then
     echo 'no value to copy to clipboard' >&2
@@ -45,22 +51,20 @@ fi
 # handle either local or remote
 if [[ -z $SSH_TTY ]]; then
 
-    if [[ -z $TMUX ]]; then
-        # local connection
-        if command -v clip.exe &>/dev/null; then
-            echo -n "$content" | clip.exe
-            exit 0
-        fi
-
-        if command -v xclip &>/dev/null; then
-            echo -n "$content" | xclip -selection clipboard
-            exit 0
-        fi
-
-        echo "clip.exe is not found" >&2
-        echo "xclip is not installed either" >&2
-        exit 1
+    # local connection
+    if command -v clip.exe &>/dev/null; then
+        echo -n "$content" | clip.exe
+        exit 0
     fi
+
+    if command -v xclip &>/dev/null; then
+        echo -n "$content" | xclip -selection clipboard
+        exit 0
+    fi
+
+    echo "clip.exe is not found" >&2
+    echo "xclip is not installed either" >&2
+    exit 1
 
 else
     # remote, have to wrap osc52
