Use the toclip exe to eliminate vimscript to send to clipboard " Use toclip to send content to clipboard if executable('toclip')     function! ToClip()         let buffer=getreg('"')         call system('toclip', buffer)     endfunction     augroup toClipBoard         autocmd!         autocmd TextYankPost * if v:event.operator ==# 'y' && v:event.regname == ''             \| call ToClip()             \| endif     augroup END endif

diff --git a/shellfunc/bin/toclip b/shellfunc/bin/toclip
--- a/shellfunc/bin/toclip
+++ b/shellfunc/bin/toclip
@@ -23,8 +23,8 @@ if [[ -z $SSH_CLIENT ]]; then
         echo -n "$content" | xclip -selection clipboard
         exit 0
     fi
-    echo "clip.exe is not found" >&1
-    echo "xclip is not installed either" >&1
+    echo "clip.exe is not found" >&2
+    echo "xclip is not installed either" >&2
     exit 1
 else
     content="$(echo -n $content | base64 -)"
